import { RestaurantArticle } from "@/types/RestaurantArticle";

export const articles: RestaurantArticle[] = [
  {
    id: 1,
    name: "Burger Végé",
    price: 10.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 2,
    name: "Burger Fish",
    price: 350.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 3,
    name: "Burger Poulet",
    price: 14.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 4,
    name: "Burger Viande",
    price: 11.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 5,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 6,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 7,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 8,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 9,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 1,
    typeProd: "",
  },
  {
    id: 10,
    name: "Burger Végé",
    price: 10.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 11,
    name: "Burger Fish",
    price: 350.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 12,
    name: "Burger Poulet",
    price: 14.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 13,
    name: "Burger Viande",
    price: 11.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 14,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 15,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 16,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 17,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
  {
    id: 18,
    name: "Smash Burger",
    price: 16.99,
    description: "Description du produit",
    imagePath: "/burger.png",
    createdAt: Date.now(),
    restaurantId: 2,
    typeProd: "",
  },
];
