  server:
    port: 4000

  spring:
    application:
      name: gateway
    cloud:
      gateway:
        mvc:
          routes:
            - id: user-service
              uri: lb://service-user
              predicates:
                - Path=/users/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://172.16.10.12:8761/eureka/



