
spring:
  main:
    allow-circular-references: true
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
  application:
    name: service-restaurant
  datasource:
    url: jdbc:sqlserver://172.16.10.12;databaseName=CESI_EATS;encrypt=false;
    username: sa
    password: CesiEat06
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 4002

jwt:
  secret: "AMINEALEXANDREGABRIELNADAAKRAMPROJECTCESI_EATS2025"

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
