"use client";
import React, { useEffect, useState } from "react";
import { useFormik } from "formik";
import { z } from "zod";
import { useParams, useRouter } from "next/navigation";
import { toast } from "react-toastify";
import Input from "@/components/helper-components/Input";
import { CustomButton } from "@/components/helper-components/CustomButton";
import LoadingSpinner from "@/components/helper-components/LoadingSpinner";
import { createMenu } from "@/utils/apiMenu";
import { useAuthStore } from "@/store/authStore";
import { Restaurant } from "@/types/Restaurants";
import { getRestaurantById } from "@/utils/apiRestaurant";

// Zod schema for validation
const menuSchema = z.object({
  name: z.string().min(1, "Veuillez renseigner ce champ"),
  description: z.string().min(1, "Veuillez renseigner ce champ"),
  priceMenu: z
    .number({ invalid_type_error: "Doit être un nombre" })
    .min(0, "Le prix doit être positif ou nul"),
});

// Infer the type from the Zod schema
type MenuFormValues = z.infer<typeof menuSchema>;

const CreateMenuPage: React.FC = () => {
  const router = useRouter();
  const accessToken = useAuthStore((state) => state.accessToken);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const { id } = useParams();
  const restaurantId = Number(id);
  const [restaurant, setRestaurant] = useState<Restaurant | null>(null);

  useEffect(() => {
    // Fetch restaurant by its ID
    const fetchRestaurant = async () => {
      if (!accessToken) {
        toast.error("Session invalide. Veuillez vous reconnecter.");
        return;
      }
      try {
        const fetchedRestaurant = await getRestaurantById(
          restaurantId,
          accessToken
        );
        setRestaurant(fetchedRestaurant);
      } catch (error) {
        console.error("Error fetching restaurant:", error);
        toast.error("Erreur lors de la récupération du restaurant.");
      }
    };
    fetchRestaurant();
  }, [accessToken, restaurantId]);

  const formik = useFormik<MenuFormValues>({
    initialValues: {
      name: "",
      description: "",
      priceMenu: 0,
    },
    validate: (values) => {
      try {
        menuSchema.parse(values);
        return {};
      } catch (error) {
        if (error instanceof z.ZodError) {
          return error.flatten().fieldErrors as {
            [key in keyof MenuFormValues]?: string[];
          };
        }
        console.error("Unexpected validation error:", error);
        return { _error: "Une erreur de validation inattendue est survenue." };
      }
    },
    onSubmit: async (values) => {
      if (!accessToken) {
        toast.error("Session invalide. Veuillez vous reconnecter.");
        return;
      }
      setIsSubmitting(true);
      setSubmitError(null);

      try {
        const menuData = {
          ...values,
          restaurant: restaurant!,
          // ID will be generated by the server
          createdAt: new Date().toISOString(),
        };

        await createMenu(menuData, accessToken);

        toast.success("Menu créé avec succès !");
        formik.resetForm();
        router.push(`/restaurants/my-restaurants/${id}`);
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } catch (error: any) {
        console.error("Error creating menu:", error);
        setSubmitError(
          `Échec de la création du menu: ${error.message || "Erreur inconnue"}`
        );
      } finally {
        setIsSubmitting(false);
      }
    },
    validateOnChange: true,
    validateOnBlur: true,
  });

  const getInputClass = (fieldName: keyof MenuFormValues) => {
    return `w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-1 ${
      formik.touched[fieldName] && formik.errors[fieldName]
        ? "border-red-500 focus:ring-red-500 focus:border-red-500"
        : "border-gray-300 focus:ring-indigo-500 focus:border-indigo-500"
    }`;
  };

  return (
    <div className="flex flex-col min-h-screen bg-gray-50 py-10">
      <main className="flex-grow flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-2xl bg-white p-6 sm:p-8 shadow-lg rounded-xl space-y-6">
          <h2 className="text-center text-2xl sm:text-3xl font-extrabold text-gray-900">
            Créer un nouveau menu
          </h2>
          {submitError && (
            <div className="p-3 bg-red-100 text-red-700 border border-red-300 rounded-md w-full text-center text-sm">
              {submitError}
            </div>
          )}
          <form className="space-y-5" onSubmit={formik.handleSubmit} noValidate>
            <div>
              <Input
                label="Nom du menu *"
                id="name"
                name="name"
                type="text"
                placeholder="Nom du menu"
                value={formik.values.name}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                className={getInputClass("name")}
                error={
                  formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : undefined
                }
              />
            </div>
            <div>
              <label
                htmlFor="description"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Description *
              </label>
              <textarea
                id="description"
                name="description"
                placeholder="Description du menu"
                value={formik.values.description}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                rows={4}
                className={getInputClass("description")}
              />
              {formik.touched.description && formik.errors.description && (
                <p className="mt-1 text-xs text-red-600">
                  {formik.errors.description}
                </p>
              )}
            </div>
            <div>
              <Input
                label="Prix du menu (€) *"
                id="priceMenu"
                name="priceMenu"
                type="number"
                placeholder="Prix du menu"
                value={String(formik.values.priceMenu)}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                className={getInputClass("priceMenu")}
                min="0"
                step="0.01"
                error={
                  formik.touched.priceMenu && formik.errors.priceMenu
                    ? String(formik.errors.priceMenu)
                    : undefined
                }
              />
            </div>
            <CustomButton
              type="submit"
              disabled={isSubmitting || !formik.isValid || !formik.dirty}
              className="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white button-primary-50"
            >
              {isSubmitting ? (
                <>
                  <LoadingSpinner />
                  Création en cours...
                </>
              ) : (
                "Créer le menu"
              )}
            </CustomButton>
          </form>
        </div>
      </main>
    </div>
  );
};

export default CreateMenuPage;
