# Connexion à SQL Server
spring.datasource.url=jdbc:sqlserver://ITEM-S121587;databaseName=CESI_EATS;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=sopraSQLSERVER2019

# Configuration Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
