spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
  application:
    name: service-user
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=CESI_EATS;encrypt=false;
    username: sa
    password: sopraSQLSERVER2019
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver




server:
  port: 4001

jwt:
  secret: "AMINEALEXANDREGABRIELNADAAKRAMPROJECTCESI_EATS2025"

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
